"""add claims table

Revision ID: 0ab3ffbdb51a
Revises: 648870152f8b
Create Date: 2025-10-14 17:54:45.153487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ab3ffbdb51a'
down_revision: Union[str, Sequence[str], None] = '648870152f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_claims_code'), table_name='claims')
    op.drop_index(op.f('ix_public_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_public_claims_patient_name'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_public_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_public_appointment_requests_id'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_constraint(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_sessions', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('appointments_doctor_user_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_appointment_session_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_icd_code_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patient_profile_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'icd_codes', ['icd_code_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', type_='foreignkey')
    op.create_foreign_key(None, 'availability_templates', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversations_hospital_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('departments_hospital_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.drop_constraint(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_profiles', 'departments', ['department_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('hospitals_admin_user_id_fkey'), 'hospitals', type_='foreignkey')
    op.create_foreign_key(None, 'hospitals', 'users', ['admin_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medical_history_patient_profile_id_fkey'), 'medical_history', type_='foreignkey')
    op.create_foreign_key(None, 'medical_history', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('prescriptions_patient_user_id_fkey'), 'prescriptions', type_='foreignkey')
    op.drop_constraint(op.f('prescriptions_appointment_id_fkey'), 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'users', ['patient_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'prescriptions', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', type_='foreignkey')
    op.create_foreign_key(None, 'soap_notes', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('vitals_appointment_id_fkey'), 'vitals', type_='foreignkey')
    op.create_foreign_key(None, 'vitals', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('vitals_appointment_id_fkey'), 'vitals', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'soap_notes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'])
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(None, 'prescriptions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('prescriptions_appointment_id_fkey'), 'prescriptions', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(op.f('prescriptions_patient_user_id_fkey'), 'prescriptions', 'users', ['patient_user_id'], ['id'])
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'medical_history', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medical_history_patient_profile_id_fkey'), 'medical_history', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.drop_constraint(None, 'hospitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('hospitals_admin_user_id_fkey'), 'hospitals', 'users', ['admin_user_id'], ['id'])
    op.drop_constraint(None, 'google_auth_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'departments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('departments_hospital_id_fkey'), 'departments', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_hospital_id_fkey'), 'conversations', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'availability_templates', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_profile_id_fkey'), 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.create_foreign_key(op.f('appointments_icd_code_id_fkey'), 'appointments', 'icd_codes', ['icd_code_id'], ['id'])
    op.create_foreign_key(op.f('appointments_appointment_session_id_fkey'), 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_user_id_fkey'), 'appointments', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'appointment_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', 'users', ['doctor_user_id'], ['id'])
    op.create_table('appointment_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('appointment_requests_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('appointment_requests_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_requests_pkey'))
    )
    op.create_index(op.f('ix_public_appointment_requests_id'), 'appointment_requests', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hemoglobin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wbc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('glucose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creatinine', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('alt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cholesterol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('lab_results_patient_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_results_pkey'))
    )
    op.create_index(op.f('ix_public_lab_results_id'), 'lab_results', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'declined', name='claimstatus'), autoincrement=False, nullable=True),
    sa.Column('doctor_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason_for_denial', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('claims_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claims_pkey'))
    )
    op.create_index(op.f('ix_public_claims_patient_name'), 'claims', ['patient_name'], unique=False)
    op.create_index(op.f('ix_public_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_public_claims_code'), 'claims', ['code'], unique=False)
    # ### end Alembic commands ###
