"""slot enhancement for watlist

Revision ID: 72bcbc9a9beb
Revises: e54cc2866642
Create Date: 2025-11-29 12:40:42.569217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72bcbc9a9beb'
down_revision: Union[str, Sequence[str], None] = 'e54cc2866642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_user_signatures_id'), table_name='user_signatures')
    op.drop_table('user_signatures')
    op.drop_index(op.f('ix_public_handoff_notes_id'), table_name='handoff_notes')
    op.drop_table('handoff_notes')
    op.drop_index(op.f('ix_public_appointment_icd_codes_id'), table_name='appointment_icd_codes')
    op.drop_table('appointment_icd_codes')
    # Drop bill_items first (child table with FK to bills)
    op.drop_index(op.f('ix_public_bill_items_id'), table_name='bill_items')
    op.drop_table('bill_items')
    # Then drop bills (parent table)
    op.drop_index(op.f('ix_public_bills_bill_number'), table_name='bills')
    op.drop_index(op.f('ix_public_bills_id'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_public_lab_results_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_public_appointment_requests_id'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    op.drop_index(op.f('ix_public_patient_tasks_id'), table_name='patient_tasks')
    op.drop_table('patient_tasks')
    op.drop_index(op.f('ix_public_discharge_summaries_id'), table_name='discharge_summaries')
    op.drop_table('discharge_summaries')
    op.drop_index(op.f('ix_public_claims_code'), table_name='claims')
    op.drop_index(op.f('ix_public_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_public_claims_patient_name'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_public_patient_summaries_id'), table_name='patient_summaries')
    op.drop_table('patient_summaries')
    op.drop_constraint(op.f('appointment_sessions_parent_session_id_fkey'), 'appointment_sessions', type_='foreignkey')
    op.drop_constraint(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_sessions', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointment_sessions', 'appointment_sessions', ['parent_session_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('appointment_slots_session_id_fkey'), 'appointment_slots', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_slots', 'appointment_sessions', ['session_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.drop_constraint(op.f('appointments_appointment_slot_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_appointment_session_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_icd_code_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_user_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_patient_profile_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'icd_codes', ['icd_code_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'appointment_slots', ['appointment_slot_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', type_='foreignkey')
    op.create_foreign_key(None, 'availability_templates', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversations_hospital_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('departments_hospital_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.drop_constraint(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profiles', 'departments', ['department_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('hospitals_admin_user_id_fkey'), 'hospitals', type_='foreignkey')
    op.create_foreign_key(None, 'hospitals', 'users', ['admin_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medical_history_patient_profile_id_fkey'), 'medical_history', type_='foreignkey')
    op.create_foreign_key(None, 'medical_history', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('prescriptions_appointment_id_fkey'), 'prescriptions', type_='foreignkey')
    op.drop_constraint(op.f('prescriptions_patient_user_id_fkey'), 'prescriptions', type_='foreignkey')
    op.create_foreign_key(None, 'prescriptions', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'prescriptions', 'users', ['patient_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('session_recurrence_patterns_doctor_user_id_fkey'), 'session_recurrence_patterns', type_='foreignkey')
    op.create_foreign_key(None, 'session_recurrence_patterns', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', type_='foreignkey')
    op.create_foreign_key(None, 'soap_notes', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('vitals_appointment_id_fkey'), 'vitals', type_='foreignkey')
    op.create_foreign_key(None, 'vitals', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('waitlist_booking_tokens_waitlist_entry_id_fkey'), 'waitlist_booking_tokens', type_='foreignkey')
    op.drop_constraint(op.f('waitlist_booking_tokens_appointment_slot_id_fkey'), 'waitlist_booking_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'waitlist_booking_tokens', 'appointment_slots', ['appointment_slot_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'waitlist_booking_tokens', 'waitlist_entries', ['waitlist_entry_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('waitlist_entries_patient_profile_id_fkey'), 'waitlist_entries', type_='foreignkey')
    op.drop_constraint(op.f('waitlist_entries_updated_by_user_id_fkey'), 'waitlist_entries', type_='foreignkey')
    op.drop_constraint(op.f('waitlist_entries_created_by_user_id_fkey'), 'waitlist_entries', type_='foreignkey')
    op.drop_constraint(op.f('waitlist_entries_doctor_user_id_fkey'), 'waitlist_entries', type_='foreignkey')
    op.create_foreign_key(None, 'waitlist_entries', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'waitlist_entries', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'waitlist_entries', 'users', ['created_by_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'waitlist_entries', 'users', ['updated_by_user_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist_entries', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'waitlist_entries', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'waitlist_entries', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'waitlist_entries', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('waitlist_entries_doctor_user_id_fkey'), 'waitlist_entries', 'users', ['doctor_user_id'], ['id'])
    op.create_foreign_key(op.f('waitlist_entries_created_by_user_id_fkey'), 'waitlist_entries', 'users', ['created_by_user_id'], ['id'])
    op.create_foreign_key(op.f('waitlist_entries_updated_by_user_id_fkey'), 'waitlist_entries', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(op.f('waitlist_entries_patient_profile_id_fkey'), 'waitlist_entries', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.drop_constraint(None, 'waitlist_booking_tokens', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'waitlist_booking_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('waitlist_booking_tokens_appointment_slot_id_fkey'), 'waitlist_booking_tokens', 'appointment_slots', ['appointment_slot_id'], ['id'])
    op.create_foreign_key(op.f('waitlist_booking_tokens_waitlist_entry_id_fkey'), 'waitlist_booking_tokens', 'waitlist_entries', ['waitlist_entry_id'], ['id'])
    op.drop_constraint(None, 'vitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('vitals_appointment_id_fkey'), 'vitals', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'soap_notes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'session_recurrence_patterns', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('session_recurrence_patterns_doctor_user_id_fkey'), 'session_recurrence_patterns', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'])
    op.create_foreign_key(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(None, 'prescriptions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'prescriptions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('prescriptions_patient_user_id_fkey'), 'prescriptions', 'users', ['patient_user_id'], ['id'])
    op.create_foreign_key(op.f('prescriptions_appointment_id_fkey'), 'prescriptions', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'medical_history', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medical_history_patient_profile_id_fkey'), 'medical_history', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.drop_constraint(None, 'hospitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('hospitals_admin_user_id_fkey'), 'hospitals', 'users', ['admin_user_id'], ['id'])
    op.drop_constraint(None, 'google_auth_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'departments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('departments_hospital_id_fkey'), 'departments', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_hospital_id_fkey'), 'conversations', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'availability_templates', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_profile_id_fkey'), 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.create_foreign_key(op.f('appointments_doctor_user_id_fkey'), 'appointments', 'users', ['doctor_user_id'], ['id'])
    op.create_foreign_key(op.f('appointments_icd_code_id_fkey'), 'appointments', 'icd_codes', ['icd_code_id'], ['id'])
    op.create_foreign_key(op.f('appointments_appointment_session_id_fkey'), 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'])
    op.create_foreign_key(op.f('appointments_appointment_slot_id_fkey'), 'appointments', 'appointment_slots', ['appointment_slot_id'], ['id'])
    op.drop_constraint(None, 'appointment_slots', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_slots_session_id_fkey'), 'appointment_slots', 'appointment_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'appointment_sessions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointment_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', 'users', ['doctor_user_id'], ['id'])
    op.create_foreign_key(op.f('appointment_sessions_parent_session_id_fkey'), 'appointment_sessions', 'appointment_sessions', ['parent_session_id'], ['id'])
    op.create_table('patient_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('summary_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('ai_generated_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('what_we_found', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('what_it_means', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('your_diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('your_treatment_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('your_medications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('what_to_watch_for', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_steps', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lifestyle_tips', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('questions_to_ask', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('doctor_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('special_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('word_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_by_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_viewed_by_patient', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], name=op.f('patient_summaries_doctor_user_id_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('patient_summaries_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('patient_summaries_patient_user_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_admin_id'], ['users.id'], name=op.f('patient_summaries_signed_by_admin_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_doctor_id'], ['users.id'], name=op.f('patient_summaries_signed_by_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_staff_id'], ['users.id'], name=op.f('patient_summaries_signed_by_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_summaries_pkey'))
    )
    op.create_index(op.f('ix_public_patient_summaries_id'), 'patient_summaries', ['id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'declined', name='claimstatus'), autoincrement=False, nullable=True),
    sa.Column('doctor_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('insurance_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reason_for_denial', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('claims_appointment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('claims_pkey'))
    )
    op.create_index(op.f('ix_public_claims_patient_name'), 'claims', ['patient_name'], unique=False)
    op.create_index(op.f('ix_public_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_public_claims_code'), 'claims', ['code'], unique=False)
    op.create_table('discharge_summaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admission_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('discharge_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('chief_complaint', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('history_of_present_illness', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('past_medical_history', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('medications_on_admission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('physical_examination', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vital_signs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hospital_course', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('procedures_performed', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lab_results_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('secondary_diagnosis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('condition_on_discharge', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('discharge_medications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('discharge_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('follow_up_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('diet_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('activity_restrictions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('complications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('consultations', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('word_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_by_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_finalized', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_doctor_id'], ['users.id'], name=op.f('discharge_summaries_created_by_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('discharge_summaries_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('discharge_summaries_patient_user_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_admin_id'], ['users.id'], name=op.f('discharge_summaries_signed_by_admin_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_doctor_id'], ['users.id'], name=op.f('discharge_summaries_signed_by_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_staff_id'], ['users.id'], name=op.f('discharge_summaries_signed_by_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('discharge_summaries_pkey'))
    )
    op.create_index(op.f('ix_public_discharge_summaries_id'), 'discharge_summaries', ['id'], unique=False)
    op.create_table('patient_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_group_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('task_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('patient_tasks_created_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('patient_tasks_patient_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('patient_tasks_pkey'))
    )
    op.create_index(op.f('ix_public_patient_tasks_id'), 'patient_tasks', ['id'], unique=False)
    op.create_table('appointment_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor_profiles.id'], name=op.f('appointment_requests_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], name=op.f('appointment_requests_patient_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_requests_pkey'))
    )
    op.create_index(op.f('ix_public_appointment_requests_id'), 'appointment_requests', ['id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('result_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hemoglobin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('wbc', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('glucose', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('creatinine', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('alt', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cholesterol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('lab_results_patient_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('lab_results_pkey'))
    )
    op.create_index(op.f('ix_public_lab_results_id'), 'lab_results', ['id'], unique=False)
    # Create bills first (parent table)
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bill_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('paid_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('outstanding_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'paid', 'overdue', 'cancelled', 'partially_paid', name='billingstatus'), autoincrement=False, nullable=False),
    sa.Column('issue_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('paid_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stripe_charge_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('bills_created_by_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('bills_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], name=op.f('bills_patient_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bills_pkey'))
    )
    op.create_index(op.f('ix_public_bills_id'), 'bills', ['id'], unique=False)
    op.create_index(op.f('ix_public_bills_bill_number'), 'bills', ['bill_number'], unique=True)
    # Then create bill_items (child table with FK to bills)
    op.create_table('bill_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('icd_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icd_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('bill_items_appointment_id_fkey')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('bill_items_bill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bill_items_pkey'))
    )
    op.create_index(op.f('ix_public_bill_items_id'), 'bill_items', ['id'], unique=False)
    op.create_table('appointment_icd_codes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('icd_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('added_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['added_by_user_id'], ['users.id'], name=op.f('appointment_icd_codes_added_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name=op.f('appointment_icd_codes_appointment_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['icd_code_id'], ['icd_codes.id'], name=op.f('appointment_icd_codes_icd_code_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('appointment_icd_codes_pkey'))
    )
    op.create_index(op.f('ix_public_appointment_icd_codes_id'), 'appointment_icd_codes', ['id'], unique=False)
    op.create_table('handoff_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hospital_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('handoff_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('shift_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shift_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ai_generated_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_condition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active_problems', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('recent_changes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_medications', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pending_tasks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('important_alerts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('care_plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('family_communication', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('special_instructions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('patient_context_snapshot', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pdf_file_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('signed_by_doctor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('doctor_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('staff_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('admin_signed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_staff_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_staff_id'], ['users.id'], name=op.f('handoff_notes_acknowledged_by_staff_id_fkey')),
    sa.ForeignKeyConstraint(['created_by_staff_id'], ['users.id'], name=op.f('handoff_notes_created_by_staff_id_fkey')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('handoff_notes_hospital_id_fkey')),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], name=op.f('handoff_notes_patient_user_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_admin_id'], ['users.id'], name=op.f('handoff_notes_signed_by_admin_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_doctor_id'], ['users.id'], name=op.f('handoff_notes_signed_by_doctor_id_fkey')),
    sa.ForeignKeyConstraint(['signed_by_staff_id'], ['users.id'], name=op.f('handoff_notes_signed_by_staff_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('handoff_notes_pkey'))
    )
    op.create_index(op.f('ix_public_handoff_notes_id'), 'handoff_notes', ['id'], unique=False)
    op.create_table('user_signatures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('signature_file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_signatures_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_signatures_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_signatures_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_public_user_signatures_id'), 'user_signatures', ['id'], unique=False)
    # ### end Alembic commands ###
