"""removed patient attribute from soap notes

Revision ID: bc07bd3d60f0
Revises: f82aef65135d
Create Date: 2025-10-07 16:14:19.126888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc07bd3d60f0'
down_revision: Union[str, Sequence[str], None] = 'f82aef65135d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'appointment_sessions', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('appointments_patient_profile_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_appointment_session_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_user_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', type_='foreignkey')
    op.create_foreign_key(None, 'availability_templates', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.drop_constraint(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_participants', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'conversation_participants', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('conversations_hospital_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('departments_hospital_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.drop_constraint(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'doctor_profiles', 'departments', ['department_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('hospitals_admin_user_id_fkey'), 'hospitals', type_='foreignkey')
    op.create_foreign_key(None, 'hospitals', 'users', ['admin_user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('medical_histories_patient_profile_id_fkey'), 'medical_histories', type_='foreignkey')
    op.create_foreign_key(None, 'medical_histories', 'patient_profiles', ['patient_profile_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.drop_constraint(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_permissions_permission_id_fkey'), 'role_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_permissions_role_id_fkey'), 'role_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.drop_constraint(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', type_='foreignkey')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('soap_notes_patient_id_fkey'), 'soap_notes', type_='foreignkey')
    op.drop_constraint(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', type_='foreignkey')
    op.create_foreign_key(None, 'soap_notes', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_column('soap_notes', 'patient_id')
    op.drop_constraint(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.drop_constraint(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'staff_profiles', 'hospitals', ['hospital_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'staff_profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('users_role_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('vitals_appointment_id_fkey'), 'vitals', type_='foreignkey')
    op.create_foreign_key(None, 'vitals', 'appointments', ['appointment_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('vitals_appointment_id_fkey'), 'vitals', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('users_role_id_fkey'), 'users', 'roles', ['role_id'], ['id'])
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'staff_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('staff_profiles_hospital_id_fkey'), 'staff_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('staff_profiles_user_id_fkey'), 'staff_profiles', 'users', ['user_id'], ['id'])
    op.add_column('soap_notes', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'soap_notes', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('soap_notes_appointment_id_fkey'), 'soap_notes', 'appointments', ['appointment_id'], ['id'])
    op.create_foreign_key(op.f('soap_notes_patient_id_fkey'), 'soap_notes', 'patient_profiles', ['patient_id'], ['id'])
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_tracker_column_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_tracker_column_permissions_role_id_fkey'), 'role_tracker_column_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_tracker_column_permissions_tracker_column_id_fkey'), 'role_tracker_column_permissions', 'tracker_columns', ['tracker_column_id'], ['id'])
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('role_permissions_role_id_fkey'), 'role_permissions', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(op.f('role_permissions_permission_id_fkey'), 'role_permissions', 'permissions', ['permission_id'], ['id'])
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'patient_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_assigned_doctor_id_fkey'), 'patient_profiles', 'users', ['assigned_doctor_id'], ['id'])
    op.create_foreign_key(op.f('patient_profiles_hospital_id_fkey'), 'patient_profiles', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'messages', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['id'])
    op.drop_constraint(None, 'medical_histories', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('medical_histories_patient_profile_id_fkey'), 'medical_histories', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.drop_constraint(None, 'hospitals', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('hospitals_admin_user_id_fkey'), 'hospitals', 'users', ['admin_user_id'], ['id'])
    op.drop_constraint(None, 'google_auth_tokens', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('google_auth_tokens_doctor_user_id_fkey'), 'google_auth_tokens', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'doctor_profiles', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_profiles_user_id_fkey'), 'doctor_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('doctor_profiles_department_id_fkey'), 'doctor_profiles', 'departments', ['department_id'], ['id'])
    op.drop_constraint(None, 'departments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('departments_hospital_id_fkey'), 'departments', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversations', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_hospital_id_fkey'), 'conversations', 'hospitals', ['hospital_id'], ['id'])
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'conversation_participants', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('conversation_participants_user_id_fkey'), 'conversation_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('conversation_participants_conversation_id_fkey'), 'conversation_participants', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'availability_templates', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('availability_templates_doctor_user_id_fkey'), 'availability_templates', 'users', ['doctor_user_id'], ['id'])
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'appointments', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctor_user_id_fkey'), 'appointments', 'users', ['doctor_user_id'], ['id'])
    op.create_foreign_key(op.f('appointments_appointment_session_id_fkey'), 'appointments', 'appointment_sessions', ['appointment_session_id'], ['id'])
    op.create_foreign_key(op.f('appointments_patient_profile_id_fkey'), 'appointments', 'patient_profiles', ['patient_profile_id'], ['id'])
    op.drop_constraint(None, 'appointment_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('appointment_sessions_doctor_user_id_fkey'), 'appointment_sessions', 'users', ['doctor_user_id'], ['id'])
    # ### end Alembic commands ###
