"""create initial tables

Revision ID: b3a5b1c8d4f9
Revises: 
Create Date: 2025-09-29 17:55:12.345678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a5b1c8d4f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tables are created in an order that respects foreign key constraints.

    op.create_table('permissions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('isactive', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('updated_at', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)

    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('isactive', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('updated_at', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)

    op.create_table('tracker_columns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('column_key', sa.String(), nullable=False),
        sa.Column('display_name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('column_key')
    )
    op.create_index(op.f('ix_tracker_columns_id'), 'tracker_columns', ['id'], unique=False)

    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=True),
        sa.Column('last_name', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.String(), nullable=True),
        sa.Column('updated_at', sa.String(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)

    op.create_table('availability_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_user_id', sa.Integer(), nullable=True),
        sa.Column('day_of_week', sa.String(), nullable=False),
        sa.Column('start_time', sa.Time(), nullable=False),
        sa.Column('end_time', sa.Time(), nullable=False),
        sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
        sa.Column('is_telemedicine', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_templates_id'), 'availability_templates', ['id'], unique=False)

    op.create_table('google_auth_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_user_id', sa.Integer(), nullable=True),
        sa.Column('refresh_token', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('doctor_user_id')
    )
    op.create_index(op.f('ix_google_auth_tokens_id'), 'google_auth_tokens', ['id'], unique=False)

    op.create_table('hospitals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('time_zone', sa.String(), nullable=True),
        sa.Column('primary_language', sa.String(), nullable=True),
        sa.Column('header_text', sa.String(), nullable=True),
        sa.Column('tagline', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('favicon_url', sa.String(), nullable=True),
        sa.Column('sidebar_color', sa.String(), nullable=True),
        sa.Column('header_color', sa.String(), nullable=True),
        sa.Column('admin_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('admin_user_id'),
        sa.UniqueConstraint('code'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_hospitals_id'), 'hospitals', ['id'], unique=False)

    op.create_table('role_permissions',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )

    op.create_table('role_tracker_column_permissions',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('tracker_column_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.ForeignKeyConstraint(['tracker_column_id'], ['tracker_columns.id'], ),
        sa.PrimaryKeyConstraint('role_id', 'tracker_column_id')
    )

    op.create_table('conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('hospital_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)

    op.create_table('departments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('no_of_members', sa.Integer(), nullable=True),
        sa.Column('hospital_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)

    op.create_table('patient_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_type', sa.String(), nullable=True),
        sa.Column('billing_type', sa.String(), nullable=True),
        sa.Column('status', sa.Boolean(), nullable=True),
        sa.Column('insurer_name', sa.String(), nullable=True),
        sa.Column('member_id', sa.String(), nullable=True),
        sa.Column('group_id', sa.String(), nullable=True),
        sa.Column('subscriber_first_name', sa.String(), nullable=True),
        sa.Column('subscriber_last_name', sa.String(), nullable=True),
        sa.Column('subscriber_dob', sa.Date(), nullable=True),
        sa.Column('subscriber_relationship_to_patient', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('hospital_id', sa.Integer(), nullable=True),
        sa.Column('assigned_doctor_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_doctor_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_patient_profiles_id'), 'patient_profiles', ['id'], unique=False)

    op.create_table('staff_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_title', sa.String(), nullable=False),
        sa.Column('profile_picture_url', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('hospital_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_profiles_id'), 'staff_profiles', ['id'], unique=False)

    op.create_table('conversation_participants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_participants_id'), 'conversation_participants', ['id'], unique=False)

    op.create_table('doctor_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('specialization', sa.String(), nullable=True),
        sa.Column('medical_license_number', sa.String(), nullable=True),
        sa.Column('qualifications', sa.String(), nullable=True),
        sa.Column('years_of_experience', sa.Integer(), nullable=True),
        sa.Column('npi_number', sa.String(), nullable=True),
        sa.Column('dea_number', sa.String(), nullable=True),
        sa.Column('available_for_telehealth', sa.Boolean(), nullable=True),
        sa.Column('profile_picture_url', sa.String(), nullable=True),
        sa.Column('biography', sa.Text(), nullable=True),
        sa.Column('languages_spoken', sa.String(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('dea_number'),
        sa.UniqueConstraint('medical_license_number'),
        sa.UniqueConstraint('npi_number'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctor_profiles_id'), 'doctor_profiles', ['id'], unique=False)

    op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)

    op.create_table('medical_histories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_profile_id', sa.Integer(), nullable=False),
        sa.Column('allergies', sa.JSON(), nullable=True),
        sa.Column('current_medications', sa.JSON(), nullable=True),
        sa.Column('past_medical_history', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('patient_profile_id')
    )
    op.create_index(op.f('ix_medical_histories_id'), 'medical_histories', ['id'], unique=False)

    op.create_table('appointment_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doctor_user_id', sa.Integer(), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_sessions_id'), 'appointment_sessions', ['id'], unique=False)

    op.create_table('appointments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('patient_profile_id', sa.Integer(), nullable=True),
        sa.Column('doctor_user_id', sa.Integer(), nullable=True),
        sa.Column('appointment_session_id', sa.Integer(), nullable=True),
        sa.Column('is_telehealth', sa.Boolean(), nullable=True),
        sa.Column('google_meet_link', sa.String(), nullable=True),
        sa.Column('reason_for_visit', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['appointment_session_id'], ['appointment_sessions.id'], ),
        sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['patient_profile_id'], ['patient_profiles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('appointment_session_id')
    )
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)

    op.create_table('vitals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('appointment_id', sa.Integer(), nullable=False),
        sa.Column('blood_pressure', sa.String(), nullable=True),
        sa.Column('heart_rate', sa.Integer(), nullable=True),
        sa.Column('respiratory_rate', sa.Integer(), nullable=True),
        sa.Column('temperature', sa.Float(), nullable=True),
        sa.Column('oxygen_saturation', sa.Integer(), nullable=True),
        sa.Column('pain_level', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('appointment_id')
    )
    op.create_index(op.f('ix_vitals_id'), 'vitals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Tables are dropped in the reverse order of their creation.
    
    op.drop_index(op.f('ix_vitals_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_appointment_sessions_id'), table_name='appointment_sessions')
    op.drop_table('appointment_sessions')
    op.drop_index(op.f('ix_medical_histories_id'), table_name='medical_histories')
    op.drop_table('medical_histories')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_doctor_profiles_id'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_conversation_participants_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index(op.f('ix_staff_profiles_id'), table_name='staff_profiles')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_patient_profiles_id'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('role_tracker_column_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_hospitals_id'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_google_auth_tokens_id'), table_name='google_auth_tokens')
    op.drop_table('google_auth_tokens')
    op.drop_index(op.f('ix_availability_templates_id'), table_name='availability_templates')
    op.drop_table('availability_templates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracker_columns_id'), table_name='tracker_columns')
    op.drop_table('tracker_columns')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###